/*
 * Author: retrhelo <artyomliu@foxmail.com>
 *
 * Generated by Camellia-Glue. Seed: 3735928559
 */

module gen_module_seq_mix (
  input clk_slow,
  input rst_slow,
  input clk_fast,
  input rst_n_fast,
  input [31:0] din,
  output [31:0] dout_add,
  output [31:0] dout_minus
);

wire [31:0] data_845239;
wire [31:0] data_7808ca;
wire [31:0] data_82ddc2;
wire [31:0] data_ecdae7;


add1 u0_add1 (
  .din(data_5b9468),
  .dout(data_845239)
);

register u0_register (
  .clk(clk_slow),
  .rst_n(~(rst_slow)),
  .d(data_845239),
  .q(data_7808ca)
);

minus1 u0_minus1 (
  .din(data_5b9468),
  .dout(data_82ddc2)
);

register u1_register (
  .clk(clk_fast),
  .rst_n(rst_n_fast),
  .d(data_82ddc2),
  .q(data_ecdae7)
);

assign data_5b9468 = din;
assign dout_add = data_7808ca;
assign dout_minus = data_ecdae7;

endmodule
