/*
 * Generated by Camellia-Glue.
 */

module gen_module_seq (
  input clk,
  input rst,
  input clk_fast,
  input rst_n,
  input [31:0] din,
  output [31:0] dout1,
  output [31:0] dout2
);

wire [31:0] data_data_out_bd_45;
wire [31:0] data_data_out_bd_51;


register u0_register (
  .clk(clk),
  .rst_n(~(rst)),
  .d(data_bd_data_in_44),
  .q(data_data_out_bd_45)
);

register u1_register (
  .clk(clk_fast),
  .rst_n(rst_n),
  .d(data_bd_data_in_44),
  .q(data_data_out_bd_51)
);

assign data_bd_data_in_44 = din;
assign dout1 = data_data_out_bd_45;
assign dout2 = data_data_out_bd_51;

endmodule
