/*
 * Generated by Camellia-Glue.
 */

module gen_module_param (
  //  &06_module_param.t; @17
  input clk,
  input rst_n,
  // bd &06_module_param.t; @23
  input [63:0] din,
  // bd &06_module_param.t; @26
  output [64:0] dout
);

// &06_module_param.t; @36
wire [64:0] data_data_in_data_out_42;
// &06_module_param.t; @42
wire [64:0] data_data_out_bd_42;


// &06_module_param.t; @36
add1_param #(
  .in_width(64)
) adder (
  .din(data_data_in_bd_36),
  .dout(data_data_in_data_out_42)
);

// &06_module_param.t; @42
register_param #(
  .width(65)
) u0_register_param (
  .clk(clk),
  .rst_n(rst_n),
  .d(data_data_in_data_out_42),
  .q(data_data_out_bd_42)
);

// bd &06_module_param.t; @23
assign data_data_in_bd_36 = din;
// bd &06_module_param.t; @26
assign dout = data_data_out_bd_42;

endmodule
