/*
 * Generated by Camellia-Glue. Seed: 3735928559
 */

module gen_module_seq (
  input clk,
  input rst,
  input clk_fast,
  input rst_n,
  input [31:0] din,
  output [31:0] dout1,
  output [31:0] dout2
);

wire [31:0] data_845239;
wire [31:0] data_0c4f2d;


register u0_register (
  .clk(clk),
  .rst_n(~(rst)),
  .d(data_5b9468),
  .q(data_845239)
);

register u1_register (
  .clk(clk_fast),
  .rst_n(rst_n),
  .d(data_5b9468),
  .q(data_0c4f2d)
);

assign data_5b9468 = din;
assign dout1 = data_845239;
assign dout2 = data_0c4f2d;

endmodule
