/*
 * Author: Artyom Liu <artyomliu@foxmail.com>
 * License: MIT
 *
 * Generated by Camellia-Glue. Seed: 3735928559
 */

module gen_module_comb (
  input [31:0] din,
  output [31:0] dout
);

wire [31:0] tmp_data;
wire [31:0] data_845239;
wire [31:0] data_7808ca;


add1 u0_add1 (
  .din(data_5b9468),
  .dout(tmp_data)
);

add1 adder (
  .din(tmp_data),
  .dout(data_845239)
);

minus1 u0_minus1 (
  .din(data_845239),
  .dout(data_7808ca)
);

assign data_5b9468 = din;
assign dout = data_7808ca;

endmodule
