/*
 * Author: retrhelo <artyomliu@foxmail.com>
 *
 * Generated by Camellia-Glue.
 */

module gen_module_seq_mix (
  input clk_slow,
  input rst_slow,
  input clk_fast,
  input rst_n_fast,
  input [31:0] din,
  output [31:0] dout_add,
  output [31:0] dout_minus
);

wire [31:0] data_data_out_data_in_50;
wire [31:0] data_data_out_after_add1_51;
wire [31:0] data_data_in_data_out_57;
wire [31:0] data_data_out_after_minus1_57;


add1 u0_add1 (
  .din(data_data_in_bd_49),
  .dout(data_data_out_data_in_50)
);

register u0_register (
  .clk(clk_slow),
  .rst_n(~(rst_slow)),
  .d(data_data_out_data_in_50),
  .q(data_data_out_after_add1_51)
);

minus1 u0_minus1 (
  .din(data_data_in_bd_49),
  .dout(data_data_in_data_out_57)
);

register u1_register (
  .clk(clk_fast),
  .rst_n(rst_n_fast),
  .d(data_data_in_data_out_57),
  .q(data_data_out_after_minus1_57)
);

assign data_data_in_bd_49 = din;
assign dout_add = data_data_out_after_add1_51;
assign dout_minus = data_data_out_after_minus1_57;

endmodule
