/*
 * Generated by Camellia-Glue. Seed: 3735928559
 */

module gen_module_seq (
  // default &04_module_seq.t; @18
  input clk,
  input rst,
  //  &04_module_seq.t; @29
  input [31:0] din,
  //  &04_module_seq.t; @32
  output [31:0] dout1,
  // fast &04_module_seq.t; @23
  input clk_fast,
  input rst_n,
  //  &04_module_seq.t; @35
  output [31:0] dout2
);

// &04_module_seq.t; @43
wire [31:0] data_845239;
// &04_module_seq.t; @52
wire [31:0] data_0c4f2d;


// &04_module_seq.t; @43
register u0_register (
  .clk(clk),
  .rst_n(~(rst)),
  .d(data_5b9468),
  .q(data_845239)
);

// &04_module_seq.t; @52
register u1_register (
  .clk(clk_fast),
  .rst_n(rst_n),
  .d(data_5b9468),
  .q(data_0c4f2d)
);

//  &04_module_seq.t; @29
assign data_5b9468 = din;
//  &04_module_seq.t; @32
assign dout1 = data_845239;
//  &04_module_seq.t; @35
assign dout2 = data_0c4f2d;

endmodule
