/*
 * Author: Artyom Liu <artyomliu@foxmail.com>
 * License: MIT
 *
 * Generated by Camellia-Glue.
 */

module gen_module_comb (
  // data_in &03_module_comp.t; @22
  input [31:0] din,
  // data_out &03_module_comp.t; @25
  output [31:0] dout
);

// &03_module_comp.t; @32
wire [31:0] tmp_data;
// &03_module_comp.t; @33
wire [31:0] data_data_out_data_in_40;
// &03_module_comp.t; @34
wire [31:0] data_data_out_data_out_41;


// &03_module_comp.t; @32
add1 u0_add1 (
  .din(data_data_in_data_in_37),
  .dout(tmp_data)
);

// &03_module_comp.t; @33
add1 adder (
  .din(tmp_data),
  .dout(data_data_out_data_in_40)
);

// &03_module_comp.t; @34
minus1 u0_minus1 (
  .din(data_data_out_data_in_40),
  .dout(data_data_out_data_out_41)
);

// data_in &03_module_comp.t; @22
assign data_data_in_data_in_37 = din;
// data_out &03_module_comp.t; @25
assign dout = data_data_out_data_out_41;

endmodule
